### ISSUE TITLE
SRT audio doesn't work

### ISSUE THREAD

**Issue by justincp** [fzwoch/obs-gstreamer#44] opened 2021-01-12 04:22 UTC
Have the developers been able to use this to successfully receive and sync SRT video/audio sources? For example with the Larix mobile app? This works great for me for RTSP, but with SRT, the audio plays for a few seconds and then crashes. I am not an expert so it could I'm doing something wrong.

**Comment by fzwoch** [comment] 2021-01-12 08:39
You didnt't really much much information. What platform, which Gstreamer version, which pipeline are you using, etc? What exactly means "crash"?

Without steps to reproduce and a public SRT stream there is probably not much to do here. In such you case you need to make some investigations.

**Comment by fzwoch** [comment] 2021-01-25 21:13
Closing due to no feedback.

**Comment by justincp** [comment] 2021-01-31 23:04
Hi Florian,

Sorry for the delay. I can use the following command with gstreamer on the
plug-in just fine with an SRT source:

gst-launch-1.0.exe -v srtsrc uri="srt://:9712?mode=listener" ! decodebin !
audioconvert ! autoaudiosink

But the equivalent syntax with the gstreamer OBS plug-in doesn't work. The
audio ends after just a few seconds. Perhaps I am doing something wrong? Is
SRT working for your team with the plug-in? Perhaps, do you have example
syntax?

**Comment by justincp** [comment] 2021-01-31 23:14
Also, there is the free excellent app called Larix for iPhone and Android
that sends video and audio over SRT, RTSP, RTMP. If you ever are able to
get this to work with the plug-in, could be a good example for the readme.
I can get it to work with gstreamer plug-in and SRT, but not with the
plug-in.

**Comment by fzwoch** [comment] 2021-02-01 08:25
I have not made any tests with SRT. It is impossible for me to test all use case, especially when I suddenly need another 3rd party app and a phone.

If it's working with the command line there must be something wrong with the plugin. Maybe it is very windows specific. Maybe the ongoing changes in https://gitlab.com/fzwoch/obs-gstreamer/-/tree/mainloop will help in this case (there is a download link too). However this is just a very vague assumption.

To make a better guess I would need the the OBS log output with `GST_DEBUG=3` or `GST_DEBUG=4` environmental variable set (don't ask me how to do it on Windows though).

**Comment by justincp** [comment] 2021-02-07 22:23
Thank you for your thoughts.

Here are my updates:
1. I was able to get SRT audio working on a different laptop, so I think you are fine to close this issue.
2. I was able to set the environmental variable fine on Windows, but still am unsuccessful at generating a GST log file.
3. I have observed that I can synchronize 2 streams fine with the plug-in, but with 3 streams simultaneously it is not consistent. Do you have any ideas why this is the case?
4. Stability with SRT and the plug-in is currently low. I just submitted another issue with log files to hopefully help.

**Comment by fzwoch** [comment] 2021-02-08 10:51
Ok, closing this one.

Final thoughts:

2. It has been too long since I really worked with Windows. So i never know. I guess `set GST_DEBUG=3` and then launching from the same terminal. But it may be that it still launches in the background - then i don't know where the actual output goes to.

3. How do try to synchronize? If you have multiple instances of the plugin these cannot be synchronized in a reliable way. You would have to fiddle with multiple sources in one plugin instance - probably also mixing audio and video tracks as you only have only one sink of each type.

**Closed by fzwoch** 2021-02-08 10:51 UTC

**Comment by justincp** [comment] 2021-02-08 14:38
Those are wonderful ideas. Thank you Florian.
